name: Сборка плагина

on:
  workflow_call:
    inputs:
      use_composer:
        description: "Установка зависимостей композера"
        required: true
        type: boolean

      use_virions:
        description: "Установка вирионов"
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Копирование репо
        uses: actions/checkout@v4

      - name: Установка PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          tools: composer

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Подготовка среды
        run: |
          PHP_INI_PATH=$(php -i | grep 'Loaded Configuration File' | awk '{print $NF}')
          echo "Using php.ini at: $PHP_INI_PATH"
          echo "phar.readonly=0" >> "$PHP_INI_PATH"
          pip install requests

      - name: Скачивание скриптов
        run: |
          git clone --depth=1 https://github.com/BANedetta/plugin-builder.git temp_repo
          find temp_repo/scripts -type f \( -name "*.py" -o -name "*.php" \) -exec cp {} . \;
          rm -rf temp_repo
          ls -la

      - name: Подготовка вирионов
        if: ${{ inputs.use_virions }}
        run: |
          if [ -f ".virions_prepare.py" ]; then python .virions_prepare.py; else echo "Скрипт не найден"; exit 1; fi

      - name: Установка зависимостей композера
        if: ${{ inputs.use_composer }}
        run: |
          composer install --no-dev --optimize-autoloader

      - name: Внедрение автозагрузчика в отдельные потоки
        run: |
          if [ -f ".thread_autoload_injector.py" ]; then python .thread_autoload_injector.py; else echo "Скрипт не найден"; exit 1; fi

      - name: Сборка плагина
        run: |
          if [ -f ".plugin_build.php" ]; then php .plugin_build.php; else echo "Скрипт не найден"; exit 1; fi

      - name: Выгрузка артефакта
        uses: actions/upload-artifact@v4
        with:
          name: plugin.phar
          path: plugin.phar